In [3]:
import numpy as np

In [13]:
# create a NumPy array from a list
li = [1, 2, 3, 4] 
print(np.array(li))

# create a NumPy array from a tuple
tup = (5, 6, 7, 8)
print(np.array(tup))

# create a NumPy array using fromiter()
iterable = (a for a in range(8))
print(np.fromiter(iterable, float))

[1 2 3 4]
[5 6 7 8]
[0. 1. 2. 3. 4. 5. 6. 7.]


In [14]:
# create a NumPy array from a list
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
print(np.array([list_1, list_2, list_3]))

# create a NumPy array using numpy.empty()
print(np.empty([4, 3], dtype=int))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# create a NumPy array using numpy.arange()
print(np.arange(1, 10))

# create a NumPy array using numpy.linspace()
print(np.linspace(1, 10, 3))

# create a NumPy array using numpy.zeros()
print(np.zeros(5, dtype=int))

# create a NumPy array using numpy.ones()
print(np.ones(5, dtype=int))

# create a NumPy array using numpy.random.rand()
print(np.random.rand(5))

# create a NumPy array using numpy.random.randint()
print(np.random.randint(5, size=10))

[1 2 3 4 5 6 7 8 9]
[ 1.   5.5 10. ]
[0 0 0 0 0]
[1 1 1 1 1]
[0.76716503 0.99460586 0.72771467 0.62061255 0.53826351]
[0 0 4 4 4 1 4 4 1 4]


In [16]:
arr = np.asarray([1, 2, 3, 4])
# check size of the array
print("Size:", arr.size)

# check len of the array
print("len:", len(arr))

# check shape of the array
print("Shape:", arr.shape)

# check dtype of the array elements
print("Datatype:", arr.dtype)

# change the dtype to 'float64'
arr = arr.astype('float64')
print(arr)
print("Datatype:", arr.dtype)

# convert array to list
lis = arr.tolist()
print("\nList:", lis)
print(type(lis))

Size: 4
len: 4
Shape: (4,)
Datatype: int64
[1. 2. 3. 4.]
Datatype: float64

List: [1.0, 2.0, 3.0, 4.0]
<class 'list'>


In [17]:
# Two dimensional numpy array
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
arr = np.array([list_1, list_2, list_3]) 

# check size of the array
print("Size:", arr.size)

# check length of the array
print("Length:", len(arr))

# check shape of the array
print("Shape:", arr.shape)

# check dtype of the array elements
print("Datatype:", arr.dtype)

# change the dtype to 'float64'
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

# convert array to list
lis = arr.tolist()
print("\nList:", lis)
print(type(lis))

Size: 12
Length: 3
Shape: (3, 4)
Datatype: int64
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
float64

List: [[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0]]
<class 'list'>


In [18]:
# the array is saved in the file geekfile.npy
np.save("first", np.arange(5))

# the array is loaded into b
print(np.load("first.npy"))

[0 1 2 3 4]


In [19]:
x = np.arange(0, 10, 1)
print(x)

# X array saved in geekfile.txt
c = np.savetxt("first2.txt", x, delimiter =', ')

[0 1 2 3 4 5 6 7 8 9]


In [20]:
# sorting a one dimensional
# numpy array using numpy.sort()
a = np.array([12, 15, 10, 1])
print("Array before sorting",a)
a.sort()
print("Array after sorting",a)

Array before sorting [12 15 10  1]
Array after sorting [ 1 10 12 15]


In [21]:
# sorting a two dimensional
# numpy array using numpy.sort()
# sort along the first axis
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)    
print ("Along first axis : \n", arr1)    

# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)    
print ("\nAlong Last axis : \n", arr2)

a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)    
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[10  1]
 [12 15]]

Along Last axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [23]:
# Adding the values at the end
# of a numpy array
print("Original Array:", arr)

# appending to the array
arr = np.append(arr, [7])
print("Array after appending:", arr)

Original Array: [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Array after appending: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.  7.]


In [24]:
# Adding the values at the end
# of a numpy array
arr = np.arange(1, 13).reshape(2, 6)
print("Original Array")
print(arr, "\n")

# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
arr_col = np.append(arr, col, axis=0)
print("Array after appending the values column wise")
print(arr_col, "\n")

# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
arr_row = np.append(arr, row, axis=1)
print("Array after appending the values row wise")
print(arr_row)

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 

Array after appending the values row wise
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


In [25]:
arr = np.asarray([1, 2, 3, 4])
# Python Program illustrating numpy.insert()
print("1D arr:", arr)
print("Shape:", arr.shape)

# Inserting value 9 at index 1
a = np.insert(arr, 1, 9)
print("\nArray after insertion:", a)
print("Shape:", a.shape)

1D arr: [1 2 3 4]
Shape: (4,)

Array after insertion: [1 9 2 3 4]
Shape: (5,)


In [26]:
# Python Program illustrating
# numpy.delete()
print("Original arr:", arr)
print("Shape : ", arr.shape)

# deletion from 1D array
object = 2
a = np.delete(arr, object)
print("\ndeleteing the value at index {} from array:\n {}".format(object,a))
print("Shape : ", a.shape)

Original arr: [1 2 3 4]
Shape :  (4,)

deleteing the value at index 2 from array:
 [1 2 4]
Shape :  (3,)


In [27]:
# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array: " + str(array))

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped1 = array.reshape((4, array.size//4))

# printing reshaped array
print("First Reshaped Array:")
print(reshaped1)

# creating another reshaped array
reshaped2 = np.reshape(array, (2, 8))

# printing reshaped array
print("\nSecond Reshaped Array:")
print(reshaped2)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Second Reshaped Array:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [32]:
# printing array
print(" 2-D Array:")
print(arr)

# reshaping numpy array
# converting it to 1-D from 2-D array
# reshaped = arr.reshape((12))

# # printing reshaped array
# print("Reshaped 1-D Array:")
# print(reshaped)

 2-D Array:
[1 2 3 4]


In [38]:
# Two dimensional numpy array
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
arr = np.array([list_1, list_2]) 

print(arr.flatten())

[1 2 3 4 5 6 7 8]


In [39]:
# making a 3x3 array
gfg = np.array([[1, 2],
                [4, 5],
                [7, 8]])

# before transpose
print(gfg, end ='\n\n')

# after transpose
print(gfg.transpose(1, 0))

[[1 2]
 [4 5]
 [7 8]]

[[1 4 7]
 [2 5 8]]


In [4]:
arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])

# combining on axis 0
gfg = np.concatenate((arr1, arr2), axis = 0)
print(gfg)

# combining on axis 1
gfg = np.concatenate((arr1, arr2), axis = 1)
print("\n", gfg)

# combining on axis None
gfg = np.concatenate((arr1, arr2), axis = None)
print("\n", gfg)

# stacking two arrays on one another
print(np.stack((arr1, arr2), axis=1))

[[2 4]
 [6 8]
 [3 5]
 [7 9]]

 [[2 4 3 5]
 [6 8 7 9]]

 [2 4 6 8 3 5 7 9]
[[[2 4]
  [3 5]]

 [[6 8]
  [7 9]]]


In [6]:
arr = np.array([[2, 4], [6, 8]])
print(arr)

# a[start:stop:step]
print("a[-2:7:1] = ",arr[-2:7:1])

print("a[1:] = ",arr[1:])

[[2 4]
 [6 8]]
a[-2:7:1] =  [[2 4]
 [6 8]]
a[1:] =  [[6 8]]


In [7]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing addition using numpy function
print("Addition:", np.add(a, b))

# Performing subtraction using numpy function
print("Subtraction:", np.subtract(a, b))

# Performing multiplication using numpy function
print("Multiplication:", np.multiply(a, b))

# Performing division using numpy functions
print("Division:", np.divide(a, b))

# Performing mod on two matrices
print("Mod:", np.mod(a, b))

#Performing remainder on two matrices
print("Remainder:", np.remainder(a,b))

# Performing power of two matrices
print("Power:", np.power(a, b))

# Performing Exponentiation
print("Exponentiation:", np.exp(b))

Addition: [  7  77  23 130]
Subtraction: [ 3 67  3 70]
Multiplication: [  10  360  130 3000]
Division: [ 2.5        14.4         1.3         3.33333333]
Mod: [ 1  2  3 10]
Remainder: [ 1  2  3 10]
Power: [                 25          1934917632        137858491849
 1152921504606846976]
Exponentiation: [7.38905610e+00 1.48413159e+02 2.20264658e+04 1.06864746e+13]


In [10]:
arr = np.array([.5, 1.5, 2.5, 3.5, 4.5, 10.1])

# applying sqrt() method
print("Square-root:", np.sqrt(arr))

# applying log() method
print("Log Value: ", np.log(arr))

# applying absolute() method
print("Absolute Value:", np.absolute(arr))

# applying sin() method
print("Sine values:", np.sin(arr))

# applying ceil() method
print("Ceil values:", np.ceil(arr))

# applying floor() method
print("Floor Values:", np.floor(arr))

# applying round() method
print ("Rounded values:", np.round(arr))

Square-root: [0.70710678 1.22474487 1.58113883 1.87082869 2.12132034 3.17804972]
Log Value:  [-0.69314718  0.40546511  0.91629073  1.25276297  1.5040774   2.31253542]
Absolute Value: [ 0.5  1.5  2.5  3.5  4.5 10.1]
Sine values: [ 0.47942554  0.99749499  0.59847214 -0.35078323 -0.97753012 -0.62507065]
Ceil values: [ 1.  2.  3.  4.  5. 11.]
Floor Values: [ 0.  1.  2.  3.  4. 10.]
Rounded values: [ 0.  2.  2.  4.  4. 10.]


In [11]:
# 1D array
arr = [20, 2, 7, 1, 34]

# mean
print("mean of arr:", np.mean(arr))

# median
print("median of arr:", np.median(arr))

# sum
print("Sum of arr(uint8):", np.sum(arr, dtype = np.uint8))
print("Sum of arr(float32):", np.sum(arr, dtype = np.float32))

# min and max
print("maximum element:", np.max(arr))
print("minimum element:", np.min(arr))

# var
print("var of arr:", np.var(arr))
print("var of arr(float32):", np.var(arr, dtype = np.float32))

# standard deviation
print("std of arr:", np.std(arr))
print ("More precision with float32", np.std(arr, dtype = np.float32))

mean of arr: 12.8
median of arr: 7.0
Sum of arr(uint8): 64
Sum of arr(float32): 64.0
maximum element: 34
minimum element: 1
var of arr: 158.16
var of arr(float32): 158.16
std of arr: 12.576167937809991
More precision with float32 12.576168


In [12]:
# create numpy 1d-array
array1 = np.array([0, 1, 2])
array2 = np.array([3, 4, 5])

# pearson product-moment correlation
# coefficients of the arrays
rslt = np.corrcoef(array1, array2)

print(rslt)

[[1. 1.]
 [1. 1.]]
